[package]
name = "atc_lambda"
version = "0.2.0"
edition = "2021"

[dependencies]
atc_serverless = { path = "../", features = ["tracing"] }
lambda_runtime = "0.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json"] }
serde_json = "1.0"
rayon = "1.8"
