"""
Tests for I Ching prediction constants.
"""

from modules.iching.predict.constants import (
    HOA,
    KIM,
    MOC,
    THO,
    THUY,
    WU_HANG_BI_KHAC,
    WU_HANG_DICT,
    WU_HANG_DUOC_SINH,
    WU_HANG_LIST,
    WU_HANG_TUONG_KHAC,
    WU_HANG_TUONG_KHAC_PAIRS,
    WU_HANG_TUONG_SINH,
    WU_HANG_TUONG_SINH_PAIRS,
    YANG,
    YIN,
    YIN_YANG_VALUES,
)


class TestYinYangConstants:
    """Test Âm/Dương constants."""

    def test_yin_yang_values(self):
        """Test YIN_YANG_VALUES tuple."""
        assert YIN == "Âm"
        assert YANG == "Dương"
        assert YIN_YANG_VALUES == (YIN, YANG)
        assert len(YIN_YANG_VALUES) == 2


class TestWuHangConstants:
    """Test Ngũ hành constants."""

    def test_wu_hang_constants(self):
        """Test individual Ngũ hành constants."""
        assert KIM == "Kim"
        assert MOC == "Mộc"
        assert THUY == "Thuỷ"
        assert HOA == "Hoả"
        assert THO == "Thổ"

    def test_wu_hang_list(self):
        """Test WU_HANG_LIST contains all 5 elements."""
        assert len(WU_HANG_LIST) == 5
        assert MOC in WU_HANG_LIST
        assert HOA in WU_HANG_LIST
        assert THO in WU_HANG_LIST
        assert KIM in WU_HANG_LIST
        assert THUY in WU_HANG_LIST

    def test_wu_hang_dict(self):
        """Test WU_HANG_DICT mapping."""
        assert len(WU_HANG_DICT) == 5
        assert WU_HANG_DICT["Kim"] == KIM
        assert WU_HANG_DICT["Mộc"] == MOC
        assert WU_HANG_DICT["Thuỷ"] == THUY
        assert WU_HANG_DICT["Hoả"] == HOA
        assert WU_HANG_DICT["Thổ"] == THO


class TestWuHangTuongSinh:
    """Test Ngũ hành Tương sinh (Generating Cycle)."""

    def test_wu_hang_tuong_sinh_complete_cycle(self):
        """Test complete generating cycle."""
        # Thủy sinh Mộc
        assert WU_HANG_TUONG_SINH[THUY] == MOC
        # Mộc sinh Hỏa
        assert WU_HANG_TUONG_SINH[MOC] == HOA
        # Hỏa sinh Thổ
        assert WU_HANG_TUONG_SINH[HOA] == THO
        # Thổ sinh Kim
        assert WU_HANG_TUONG_SINH[THO] == KIM
        # Kim sinh Thủy
        assert WU_HANG_TUONG_SINH[KIM] == THUY

    def test_wu_hang_duoc_sinh_complete_cycle(self):
        """Test complete reverse generating cycle."""
        # Mộc được Thủy sinh
        assert WU_HANG_DUOC_SINH[MOC] == THUY
        # Hỏa được Mộc sinh
        assert WU_HANG_DUOC_SINH[HOA] == MOC
        # Thổ được Hỏa sinh
        assert WU_HANG_DUOC_SINH[THO] == HOA
        # Kim được Thổ sinh
        assert WU_HANG_DUOC_SINH[KIM] == THO
        # Thủy được Kim sinh
        assert WU_HANG_DUOC_SINH[THUY] == KIM

    def test_wu_hang_tuong_sinh_pairs(self):
        """Test WU_HANG_TUONG_SINH_PAIRS."""
        assert len(WU_HANG_TUONG_SINH_PAIRS) == 5
        assert (THUY, MOC) in WU_HANG_TUONG_SINH_PAIRS
        assert (MOC, HOA) in WU_HANG_TUONG_SINH_PAIRS
        assert (HOA, THO) in WU_HANG_TUONG_SINH_PAIRS
        assert (THO, KIM) in WU_HANG_TUONG_SINH_PAIRS
        assert (KIM, THUY) in WU_HANG_TUONG_SINH_PAIRS

    def test_wu_hang_tuong_sinh_and_duoc_sinh_consistency(self):
        """Test consistency between TUONG_SINH and DUOC_SINH."""
        # If A generates B, then B is generated by A
        for element in WU_HANG_LIST:
            generated = WU_HANG_TUONG_SINH[element]
            assert WU_HANG_DUOC_SINH[generated] == element


class TestWuHangTuongKhac:
    """Test Ngũ hành Tương khắc (Overcoming Cycle)."""

    def test_wu_hang_tuong_khac_complete_cycle(self):
        """Test complete overcoming cycle."""
        # Thủy khắc Hỏa
        assert WU_HANG_TUONG_KHAC[THUY] == HOA
        # Hỏa khắc Kim
        assert WU_HANG_TUONG_KHAC[HOA] == KIM
        # Kim khắc Mộc
        assert WU_HANG_TUONG_KHAC[KIM] == MOC
        # Mộc khắc Thổ
        assert WU_HANG_TUONG_KHAC[MOC] == THO
        # Thổ khắc Thủy
        assert WU_HANG_TUONG_KHAC[THO] == THUY

    def test_wu_hang_bi_khac_complete_cycle(self):
        """Test complete reverse overcoming cycle."""
        # Hỏa bị Thủy khắc
        assert WU_HANG_BI_KHAC[HOA] == THUY
        # Kim bị Hỏa khắc
        assert WU_HANG_BI_KHAC[KIM] == HOA
        # Mộc bị Kim khắc
        assert WU_HANG_BI_KHAC[MOC] == KIM
        # Thổ bị Mộc khắc
        assert WU_HANG_BI_KHAC[THO] == MOC
        # Thủy bị Thổ khắc
        assert WU_HANG_BI_KHAC[THUY] == THO

    def test_wu_hang_tuong_khac_pairs(self):
        """Test WU_HANG_TUONG_KHAC_PAIRS."""
        assert len(WU_HANG_TUONG_KHAC_PAIRS) == 5
        assert (THUY, HOA) in WU_HANG_TUONG_KHAC_PAIRS
        assert (HOA, KIM) in WU_HANG_TUONG_KHAC_PAIRS
        assert (KIM, MOC) in WU_HANG_TUONG_KHAC_PAIRS
        assert (MOC, THO) in WU_HANG_TUONG_KHAC_PAIRS
        assert (THO, THUY) in WU_HANG_TUONG_KHAC_PAIRS

    def test_wu_hang_tuong_khac_and_bi_khac_consistency(self):
        """Test consistency between TUONG_KHAC and BI_KHAC."""
        # If A overcomes B, then B is overcome by A
        for element in WU_HANG_LIST:
            overcome = WU_HANG_TUONG_KHAC[element]
            assert WU_HANG_BI_KHAC[overcome] == element

    def test_no_element_self_relations(self):
        """Test that no element has self-relations in any cycle (overcoming or generating)."""
        for element in WU_HANG_LIST:
            assert WU_HANG_TUONG_KHAC.get(element) != element
            assert WU_HANG_BI_KHAC.get(element) != element
            assert WU_HANG_TUONG_SINH.get(element) != element
            assert WU_HANG_DUOC_SINH.get(element) != element


class TestWuHangRelationships:
    """Test relationships between generating and overcoming cycles."""

    def test_tuong_sinh_and_tuong_khac_no_overlap(self):
        """Test that generating and overcoming don't overlap."""
        # An element cannot both generate and overcome the same element
        for element in WU_HANG_LIST:
            generated = WU_HANG_TUONG_SINH.get(element)
            overcome = WU_HANG_TUONG_KHAC.get(element)
            if generated and overcome:
                assert generated != overcome

    def test_all_elements_have_tuong_sinh(self):
        """Test that all elements have a TUONG_SINH mapping."""
        for element in WU_HANG_LIST:
            assert element in WU_HANG_TUONG_SINH
            assert element in WU_HANG_DUOC_SINH

    def test_all_elements_have_tuong_khac(self):
        """Test that all elements have a TUONG_KHAC mapping."""
        for element in WU_HANG_LIST:
            assert element in WU_HANG_TUONG_KHAC
            assert element in WU_HANG_BI_KHAC
