"""Type stubs for exchange_manager module."""

from typing import Any, ContextManager, List, Optional

import ccxt  # type: ignore[import-untyped]

class ExchangeWrapper:
    exchange: ccxt.Exchange
    def __init__(self, exchange: ccxt.Exchange) -> None: ...
    def increment_refcount(self) -> int: ...
    def decrement_refcount(self) -> int: ...
    def get_refcount(self) -> int: ...
    def is_in_use(self) -> bool: ...

class AuthenticatedExchangeManager:
    def __init__(
        self,
        api_key: Optional[str] = None,
        api_secret: Optional[str] = None,
        testnet: bool = False,
        request_pause: Optional[float] = None,
        contract_type: Optional[str] = None,
    ) -> None: ...
    def connect_to_exchange_with_credentials(
        self,
        exchange_id: str,
        api_key: Optional[str] = None,
        api_secret: Optional[str] = None,
        testnet: Optional[bool] = None,
        contract_type: Optional[str] = None,
    ) -> ccxt.Exchange: ...
    def set_exchange_credentials(self, exchange_id: str, api_key: str, api_secret: str) -> None: ...
    def cleanup_unused_exchanges(self, max_age_hours: Optional[float] = None) -> None: ...
    def release_exchange(
        self, exchange_id: str, testnet: bool = False, contract_type: Optional[str] = None
    ) -> None: ...
    def exchange_context(
        self,
        exchange_id: str,
        api_key: Optional[str] = None,
        api_secret: Optional[str] = None,
        testnet: Optional[bool] = None,
        contract_type: Optional[str] = None,
    ) -> ContextManager[ccxt.Exchange]: ...
    def throttled_call(self, func: Any, *args: Any, **kwargs: Any) -> Any: ...

class PublicExchangeManager:
    def __init__(self, request_pause: Optional[float] = None) -> None: ...
    def connect_to_exchange_with_no_credentials(self, exchange_id: str) -> ccxt.Exchange: ...
    def cleanup_unused_exchanges(self, max_age_hours: Optional[float] = None) -> None: ...
    def close_exchange(self, exchange_id: str) -> None: ...
    def throttled_call(self, func: Any, *args: Any, **kwargs: Any) -> Any: ...
    @property
    def exchange_priority_for_fallback(self) -> List[str]: ...
    @exchange_priority_for_fallback.setter
    def exchange_priority_for_fallback(self, value: List[str]) -> None: ...

class ExchangeManager:
    authenticated: AuthenticatedExchangeManager
    public: PublicExchangeManager

    def __init__(
        self,
        api_key: Optional[str] = None,
        api_secret: Optional[str] = None,
        testnet: bool = False,
    ) -> None: ...
    def normalize_symbol(self, market_symbol: str) -> str: ...
    def cleanup_unused_exchanges(self, max_age_hours: Optional[float] = None) -> None: ...
    def close_exchange(self, exchange_id: str, testnet: bool = False, contract_type: Optional[str] = None) -> None: ...
    @property
    def exchange_priority_for_fallback(self) -> List[str]: ...
    @exchange_priority_for_fallback.setter
    def exchange_priority_for_fallback(self, value: List[str]) -> None: ...

__all__: List[str]
